export const ITEM_DISPLAY_NAMES: Record<string, string> = {
  limestone: 'Limestone',
  grain: 'Grain',
  livestock: 'Livestock',
  fish: 'Fish',
  iron: 'Iron',
  coca: 'Mystery Plant',
  lead: 'Lead',
  petroleum: 'Petroleum',
  concrete: 'Concrete',
  steel: 'Steel',
  bread: 'Bread',
  steak: 'Steak',
  cookedFish: 'Cooked Fish',
  lightAmmo: 'Light Ammo',
  ammo: 'Ammo',
  cocain: 'Pill',
  oil: 'Oil',
  heavyAmmo: 'Heavy Ammo',
  knife: 'Knife',
  gun: 'Gun',
  rifle: 'Rifle',
  sniper: 'Sniper',
  tank: 'Tank',
  jet: 'Jet',
  case1: 'Case',
  case2: 'Elite Case',
  scraps: 'Scraps',
  helmet1: 'Helmet T1',
  helmet2: 'Helmet T2',
  helmet3: 'Helmet T3',
  helmet4: 'Helmet T4',
  helmet5: 'Helmet T5',
  helmet6: 'Helmet T6',
  chest1: 'Chest T1',
  chest2: 'Chest T2',
  chest3: 'Chest T3',
  chest4: 'Chest T4',
  chest5: 'Chest T5',
  chest6: 'Chest T6',
  boots1: 'Boots T1',
  boots2: 'Boots T2',
  boots3: 'Boots T3',
  boots4: 'Boots T4',
  boots5: 'Boots T5',
  boots6: 'Boots T6',
  gloves1: 'Gloves T1',
  gloves2: 'Gloves T2',
  gloves3: 'Gloves T3',
  gloves4: 'Gloves T4',
  gloves5: 'Gloves T5',
  gloves6: 'Gloves T6',
  pants1: 'Pants T1',
  pants2: 'Pants T2',
  pants3: 'Pants T3',
  pants4: 'Pants T4',
  pants5: 'Pants T5',
  pants6: 'Pants T6',
};

export function getItemDisplayName(itemCode: string): string {
  return ITEM_DISPLAY_NAMES[itemCode] || itemCode;
}
